# The URL the site will be built for
base_url = "https://chevyray.dev"

# The site title and description; used in feeds by default.
title = "Chevy Ray"
description = "Rust, programming, game development, worldbuilding, and art."

# The default language; used in feeds.
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to minify the outputted HTML
minify_html = true

# Don't process assets of this type
ignored_content = ["*.{ase,psd,afdesign}"]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Generate an RSS feed called atom.xml at the website's root
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]

# Tags
taxonomies = [
    { name = "tags", feed = true, render = true, paginate_by = 10, paginate_path = "" }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "catppuccin-latte"
#highlight_theme = "OneHalfLight"
extra_syntaxes_and_themes = ["highlighting", "highlighting/catppuccin"]
external_links_target_blank = true

[extra]
# Put all your custom variables here
